# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='tegs',
            field=models.ForeignKey(db_column='tags', null=True, on_delete=django.db.models.deletion.CASCADE, to='cod.Tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
