# Generated by Django 2.2.5 on 2019-09-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cod', '0003_auto_20190916_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cod',
            name='uid',
            field=models.TextField(blank=True, db_column='uid', null=True),
        ),
    ]
